# Generated by Django 3.1.4 on 2020-12-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201222_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
