# Generated by Django 3.1.4 on 2020-12-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
