# Generated by Django 3.1.4 on 2020-12-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201223_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='home.Tags'),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
