# Generated by Django 3.1.4 on 2020-12-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201223_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
