# Generated by Django 3.1.4 on 2020-12-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201223_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_img',
            new_name='project_img_gif',
        ),
    ]
