# Generated by Django 3.1.4 on 2020-12-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201224_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_img_static',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
